# -*- coding: utf-8 -*-
"""even odd

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OVNwdnNTnqtv3h-yEY_3mUSUnaK8ftIg
"""

n=int(input())
if n%2=0:
  print('Even')
else:
  print('Odd')

8