# -*- coding: utf-8 -*-
"""Fibnocci Series

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oinCv9J7cVWwWSNyNcPdzplzFIkhrBgf
"""

nterms = int(input("How many terms? "))


n1, n2 = 0, 1
count = 0

if nterms <= 0:
   print("Please enter a positive integer")

elif nterms == 1:
   print("Fibonacci sequence upto",nterms,":")
   print(n1)

else:
   print("Fibonacci sequence:")
   while count < nterms:
       print(n1)
       nth = n1 + n2
      
       n1 = n2
       n2 = n2
       count += 1

